
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo2
  name: demo2
  namespace: demo
spec:
  type: NodePort
  ports:
  - name: demo2
    port: 8080
    targetPort: 8082
  selector:
    app: demo2
